### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by bryan7600** [DillyzThe1/ColorCove#4]
First of all, I like how the zoom and rotate are sync'd with the music. I like that it changes cadence, which increases the difficulty (especially because I was so unlucky). Maybe some instructions, like maybe when the level starts, put up a toast with a sentence telling me who to click on? Also, where is the DONATE link? I like the original ART and MUSIC. I did not know that Uncle Fred was a baker. I hope to see him as a villain one day. Will there be a high score board? (or in my case a lowest score?)
</end>

**Comment by DillyzThe1** [comment]
A mini-tutorial is coming soon.
A donate link, however, will most likely remain absent due to me not having a way or desire to collect donations from my very few players.

Also, Uncle Fred's bakery is just an in-game joke, and he does not happen to own one in other games/mods of games.
You can view [Uncle Fred's FNF mod](https://gamebanana.com/wips/63859) or [the wiki documenting the modification](https://fridaynightfunking.fandom.com/wiki/Vs._Uncle_Fred) for more information.

**Comment by DillyzThe1** [comment]
As of v0.6.0, there is now a tutorial when clicking the "Play" button.
